service: quiz

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  environment:
    stage: ${opt:stage, self:provider.stage, 'dev'}
    JWT_PUBLIC: ${ssm:/quiz/jwt/public}
    JWT_SECRET: ${ssm:/quiz/jwt/secret}

functions:
  quizCreate:
    handler: src/edit.create
    events:
      - http:
          path: /quiz/create
          method: POST
  quizGetEdit:
    handler: src/edit.getQuizEdit
    events:
      - http:
          path: /quiz/edit/{key}
          method: GET
  quizEditMeta:
    handler: src/edit.editMeta
    events:
      - http:
          path: /quiz/edit
          method: PATCH
  addQuestion:
    handler: src/edit.addQuestion
    events:
      - http:
          path: /quiz/question/add
          method: POST
  editQuestion:
    handler: src/edit.editQuestion
    events:
      - http:
          path: /quiz/question/edit
          method: PATCH
  addAnswer:
    handler: src/edit.addAnswer
    events:
      - http:
          path: /quiz/answer/add
          method: POST
  editAnswer:
    handler: src/edit.editAnswer
    events:
      - http:
          path: /quiz/answer/edit
          method: PATCH
  deleteAnswer:
    handler: src/edit.deleteAnswer
    events:
      - http:
          path: /quiz/answer/delete
          method: DELETE

  getQuiz:
    handler: src/quiz.get
    events:
      - http:
          path: /quiz/{id}
          method: GET
          cors: true

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dynamodb-local

custom:
  serverless-offline:
    httpPort: 5000
    noPrependStageInUrl: true
  webpack:
    webpackConfig: ./webpack.config.js
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true

resources:
  Resources:
    quizTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: quiz
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
